import Head from "next/head";
import Select from "../Select";
import styles from "../../styles/Home.module.css";

export default function Layout({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mobile Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Mobile Store </h1>

        <p className={styles.description}>Selecciona tu marca Favorita</p>
        <Select />
        <div className={styles.grid}>{children}</div>
      </main>

      <footer className={styles.footer}>
        <p>Hecho por: Jamid, Diego, jaider </p>
      </footer>
    </div>
  );
}