import Head from "next/head";
import Image from "next/image";
import Card from "../components/Card";
import Select from "../components/Select";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mobile Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Mobile Store </h1>

        <p className={styles.description}>Selecciona tu marca Favorita</p>
        <Select />

        <div className={styles.grid}>
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Hecho por: </p>
      </footer>
    </div>
  );
}
