import Head from "next/head";
import Card from "../components/Card";
import Select from "../components/Select";
import styles from "../styles/Home.module.css";
import { Data } from "../data/data";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mobile Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Empresa JJD</h1>

        <p className={styles.description}>Selecciona tu marca Favorita</p>
        <Select />
        <div className={styles.grid}>
          {Data.map((item, ind) => (
            <Card
              imageURL={item.image}
              name={item.model}
              pulgadas={item.features.pulgadas}
              procesador={item.features.procesador}
              almacenamiento={item.features.rom}
              ram={item.features.ram}
              camara={item.features.camera}
              os={item.features.os}
              peso={item.features.peso}
              resolucion={item.features.resolucion}
              bateria={item.features.bateria}
              key={ind}
            />
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Hecho por: <b>Jamid Diego Jaider</b></p>
      </footer>
    </div>
  );
}
